services:
  webv1:
    build: 
      context: ./django/
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000
  
  # webv2:
  #   build: 
  #     context: ./djangoV2/
  #   command: gunicorn demo.wsgi:application --bind 0.0.0.0:8080
  #   volumes:
  #     - ./djangoV2/:/usr/src/app/
  #     - static_files:/usr/src/app/staticfiles
  #   expose:
  #     - 8080


  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - static_files:/home/app/staticfiles
      - ./nginx/conf.d/:/etc/nginx/conf.d/
volumes:
    static_files:
  # dns:
  #   build:
  #     context: ./dns/
  #   restart: always
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zone/:/etc/bind/zone/
  #   command: named -c /etc/bind/named.conf -g -u named